.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "WPA\-CUTE" "8" "April 2024" "wpaCute v0.8.5" "wpaCute"
.SH "NAME"
\fBwpa\-cute\fR \- A graphical wpa_supplicant front end
.SH "SYNOPSIS"
\fBwpa\-cute\fR [ \-i ifname ] [ \-m seconds ] [ \-N ] [ \-p path\-to\-ctrl\-sockets ] [ \-q ] [ \-t ] [\-R] [ \-W ]
.br
\fBwpa\-cute\fR [ \-h ] [\-?] [ \-\-h ] [\-\-l]
.SH "DESCRIPTION"
wpaCute is a graphical Qt front end program for interacting with wpa_supplicant\. It\'s used to query the current status and change the con‐ figuration\. It supports a subset of the command line client, wpa_cli\. Refer to the \fBwpa_cli(8)\fR man page for a comprehensive list of the interactive mode features\.
.P
Perhaps the most practical reason to use wpaCute is that it displays a status icon in the system tray\. With just one click on this, you can quickly switch networks on or off, add new ones, edit or delete them\.
.P
The aim of wpaCute is to support you when creating or editing a network connection, in such a way that only useful information is available for selection and some settings are made "secretly and undetected" automatically\. However, this still needs a little more love until it is implemented satisfactorily\.
.P
wpaCute is a fork from wpa_gui, shipped with wpa_supplicant version 2\.6
.SH "COMMAND ARGUMENTS"
.TP
\fB\-i\fR \fIifname\fR
Specify the interface that is be configured\. Without \-i choose the first interface found in the socket path which start not with \'p2p\-dev\-\' otherwise the last found interface is chosen\.
.TP
\fB\-m\fR \fIseconds\fR
Set an independent update interval in seconds for the signal strength meter\.
.IP
This value must be a positive integer\. Without \fB\-m\fR the signal meter is only updated at each status update\. See also the notes about polling and pinging\.
.TP
\fB\-N\fR
Force not to use QSocketNotifier, use only polling\. It\'s more for testing purposes\.
.TP
\fB\-p\fR \fIpath\-to\-ctrl\-sockets\fR
Change the path where control sockets should be found\.
.TP
\fB\-q\fR
Run program in the quiet mode \- do not display tray icon pop\-up messages\.
.TP
\fB\-t\fR
Start program in the system tray only (if the window manager supports it)\. By default the main status window is shown\.
.TP
\fB\-R\fR
Tell the session manager not to restart wpaCute after reboot\.
.TP
\fB\-W\fR
Unset setting \- Disable network after "WRONG_KEY"
.IP
This is a workaround to a wpa_supplicant quirk where he endless tries to connect to a wrong configured network\. There are cases where it is a good idea, but I believe it is mostly annoying due to it\'s implementation\. If I\'m wrong, use \-W to have the original behavior\. By default will now a network disabled after a "WRONG_KEY" message\.
.TP
\fB\-h, \-?\fR
Show a short help text and program information
.TP
\fB\-\-h\fR
Call \fBman\fR to display this man page you are currently reading
.TP
\fB\-\-l\fR
Print the license
.SH "NOTES ABOUT SOME GUI ELEMENTS"
.SS "Menu"
Most of the main menu items should not pose any puzzles\. Therefore just a few comments on the Settings menu\. A subset of the main menu items are also available on the \fIStatus Icon\fR\.
.TP
\fBDisable notifier\fR
Corresponds to the option \fB\-N\fR
.TP
\fBNo tray status balloon\fR
This means, when you \fBmiddle\-click\fR on the icon, the main window appears and the status page is shown\. That may in future versions change or merged with option \fB\-q\fR
.TP
\fBDisable network after wrong key\fR
Corresponds to the option \fB\-W\fR
.SS "Status Icon"
The icon changes its appearance depending on the current connection status or quality\. A single \fBleft\-click\fR on the icon show or hide the main window\. While \fBright\-clicking\fR will make a number of other actions available, like to show a Status information popup window\. That can by the way also be displayed with a \fBmiddle\-click\fR on the icon\.
.P
Hint: This Status window is now somehow obsolete\. Currently will the same, and more, information shown by just hovering the icon\.
.SS "wpaCute Main Window"
When wpaCute is called up the first time, is always the \fBNetworks\fR tab active\. All your configured networks are listed there\. To connect to a new, unknown network, press the \fBScan\fR button to search for available networks or use the \fBAdd\fR button to enter all needed data manually\.
.P
The \fBStatus\fR page displays some information about the current connection\. While on the \fBEvents\fR page not only some messages are been collected from wpa_supplicant in a human friendly way but also some other information like errors\.
.SS "Edit Network Window"
The window morphs its look to show always only what is needed, or can be used, to some selections you made\. If you encounter some misbehavior please report\.
.P
Entered secrets will not shown again when you edit a network\. Only a hint that there is a password or key saved\. This can be annoying if you try to establish a new connection and it does not work immediately\. Unfortunately, it is then not possible to check the password\. However, this is not something that wpaCute can change, wpa_supplicant does not reveal the password but only that one exists\.
.P
When you add, delete or modify a network are these changes only made in a temporary manner inside the running wpa_supplicant\. They take effect as long as the wpa_supplicant is not terminated or triggered to reload its configuration, e\.g\. by \fBF5\fR\. You have to save the changes explicit by \fBCtrl+S\fR\. This is different from the original wpa_gui\.
.P
After each change, the old network block is always removed and a new one created\. This prevents unwanted old configuration remnants from remaining\.
.P
The data in the \fBIDString\fR field will be shown in the ID column of the \fBNetworks\fR list\. This is a kind of ploy to make it easier to distinguish between identically or very similar named but different networks\.
.P
If the edit window does not offer some required settings option you need, you can also edit the configuration file by hand or using \fBwpa_cli\fR\. You can then use wpaCute to select the network on or off as usual\. Do not hesitate to fill out a bug report on the project page or directly by mail to the author\.
.SS "Event History Window"
All raw wpa_supplicant messages are collected there, but only if the window has been opened once\. This is why it is always empty the first time it is called up, regardless of how long wpaCute has been running\. Whether this is really useful remains to be seen\. Maybe if you have serious problems to set\-up a connection\.
.SS "Peers Window"
The Peers window is not maintained and almost unchanged from the original wpa_gui\. While transforming some code from old\-school C/C++ to a more Qt like style, I noticed some wpa control request that are not, or in a different way, supported by wpa_cli\. So you may encounter some disappointments\. When no one explain me in the near future what the benefit of this window is, could it be removed soon\.
.SH "THINGS OF INTEREST"
.SS "Session Management"
Until v0\.8\.4 wpaCute had no proper session support\. That means you had to add wpaCute to some auto start feature of you desktop environment with the needed options\. That could cause some trouble, in the sense that more than one was running after a reboot\. I had, for example, to add wpaCute to the list of ignored applications on the KDE session config page\.
.P
As long as your desktop environment support session restore in a way that Qt support, is that no longer needed\. Just start wpaCute with the \fICOMMAND ARGUMENTS\fR you need, and you are done\.
.P
However, there is now also the option \fB\-R\fR which should have the same effect as to add wpaCute to some ignore list of the session manager\. The session manager ask the new started application what to do in case of a system restart and the application normally says \fIrestart me of cause\fR, whereas with \fB\-R\fR the application answers \fIdon\'t autostart me\fR\.
.SS "Config File"
The configuration file can usually found at \fB~/\.config/wpaCute/wpaCute\.conf\fR\. There is actually nothing there that you have to or should set yourself\. wpaCute saves the window position and size there as \fBgeometry\fR below the group \fB[Adapter\-<iface>]\fR\. In the group \fB[Session\-<id>]\fR are relevant data listed to restore the state of wpaCute after a reboot\. Many keys has the name \fBopt\-<X>\fR and correspond to the \fICOMMAND ARGUMENTS\fR\.
.SS "Polling and Pinging"
On systems where QSocketNotifier is not supported is wpa_supplicant only polled to fetch status changes\.
.P
One ambitious development goal was to drop the need for Polling & Pinging on systems where QSocketNotifier is supported\. But it turned out that this was a road to ruin due to the lack of some \'Status Has Changed Message\' from wpa_supplicant\. And finally would than still the problem be left that wpa_supplicant could silently die without some sigh\. So, we are doomed to poll!
.P
The polling is now not done in a fixed interval but depends on current status and reach from high frequent polling in 1sec, when probably changes are on the way, down to 20sec in some static status where primarily is checked if someone is still alive\.
.P
With the main window visible is polled in 5sec\. Only in case of an fatal error is polling halted, which e\.g\. occurs when the user not belongs to the configured \'ctrl_interface_group=foo\'\.
.SH "COPYRIGHT"
.nf
This program is licensed under the BSD license (the one with advertisement clause removed)\.

wpaCute \- A graphical wpa_supplicant front end
Copyright (C) 2018, 2022, 2024, 2025 loh\.tar@googlemail\.com

wpa_gui for wpa_supplicant
Copyright (C) 2003\-2015 Jouni Malinen <j@w1\.fi> and contributors\.
.fi
.SH "SEE ALSO"
wpa_cli(8) wpa_supplicant(8)
